// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEB_ONTAP.Models;

#nullable disable

namespace WEB_ONTAP.Migrations
{
    [DbContext(typeof(OnTapDBContext))]
    [Migration("20241112035534_hehe")]
    partial class hehe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WEB_ONTAP.Models.DACT", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DuAnID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("NhanVienID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DuAnID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("DACTs");
                });

            modelBuilder.Entity("WEB_ONTAP.Models.DuAn", b =>
                {
                    b.Property<string>("MaDA")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenDA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaDA");

                    b.ToTable("DuAns");
                });

            modelBuilder.Entity("WEB_ONTAP.Models.NhanVien", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tuoi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("WEB_ONTAP.Models.DACT", b =>
                {
                    b.HasOne("WEB_ONTAP.Models.DuAn", "DuAn")
                        .WithMany("DACTs")
                        .HasForeignKey("DuAnID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WEB_ONTAP.Models.NhanVien", "NhanVien")
                        .WithMany("DACTs")
                        .HasForeignKey("NhanVienID");

                    b.Navigation("DuAn");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("WEB_ONTAP.Models.DuAn", b =>
                {
                    b.Navigation("DACTs");
                });

            modelBuilder.Entity("WEB_ONTAP.Models.NhanVien", b =>
                {
                    b.Navigation("DACTs");
                });
#pragma warning restore 612, 618
        }
    }
}
